Сделал 6 урок
aloygolone/2ndCourseHw pull request #4
Opened 2023-11-11 17:31 UTC by aloygolone

2023-11-12 10:28 UTC, Mielilon approved these changes

2023-11-12 10:28 UTC, Mielilon commented on logiktask/hw-6/hw6.js
> +	if (numbs[i-1] == 10) break;
Проверка `numbs[i-1] == 10` смотрит на предыдущий элемент, а не на текущий. Это приведет к тому, что элемент со значением 10 будет выведен перед прерыванием цикла. Нужно использовать `numbs[i] == 10.`

2023-11-12 10:28 UTC, Mielilon commented on logiktask/hw-6/hw6.js
> +for (let i = 0; i+1 < arrayNumbs.length; i++) {
В условии цикла for должно быть` i < arrayNumbs.length - 1`, чтобы избежать выхода за пределы массива. Также, можно упростить код, убрав лишние переменные a и b, используя напрямую `arrayNumbs[i]` и `arrayNumbs[i + 1]`.

2023-11-12 10:29 UTC, Mielilon requested changes

2023-11-12 10:29 UTC, Mielilon commented on logiktask/hw-6/hw6.js
> +const d = [
По условию задачи нужно создать двумерный массив с помощью вложенных циклов. Вложенный цикл – конечное значение, стартовое – пустой массив.

2023-11-12 14:58 UTC, aloygolone commented on logiktask/hw-6/hw6.js
> +	if (numbs[i-1] == 10) break;
в том-то и дело. в задании написано, что 10 должно вывестись в консоль и после этого должно произойти прерывание. я делал как в уроках: ставил numbs[i] == 10 - в итоге в консоль выводилось 4, выполнение прерывалось, а 10 в консоль уже не попадало. поэтому я ломал голову, как это реализовать - и реализовал таким образом, как выше. Иначе 10 не выводится в консоль

2023-11-12 15:02 UTC, aloygolone commented on logiktask/hw-6/hw6.js
> +for (let i = 0; i+1 < arrayNumbs.length; i++) {
с упрощением кода согласен, а вот по поводу первого замечания - чем плоха моя версия, если она работает (в консоль выводится все, как положено)

2023-11-26 14:21 UTC, Mielilon commented on logiktask/hw-6/hw6.js
> +	if (numbs[i-1] == 10) break;
Предлагаю в таком случае поступить иначе и сделать вывод значения в консоль до того, как отработает условие, то есть, до `if`. В этом случае можно будет сделать `numbs[i] == 10`

2023-11-26 14:22 UTC, mielilon commented on logiktask/hw-6/hw6.js
> +for (let i = 0; i+1 < arrayNumbs.length; i++) {
Такой вариант, который предложила выше, он более нагляден и часто встречается на практике.

2023-12-10 08:11 UTC, merged